# Should we use multisite?
# (Set to Yes for subdirectories)
# Values: No, Yes, subdomains
multisite: Yes

# PHP version
# Values: 5.6, 7.0, 7.1 (or 5.6.30)
php: 7.1

# Paths
#
# If transplanting Chassis into an existing project, you can set these manually.
# These can be set to absolute paths, or relative paths.
paths:
    # Base directory for reference. Relative to the Chassis directory.
    base: .

    # Where WordPress lives. Relative to the base directory.
    wp: wp

    # Content directory. Relative to the base directory.
    # place symbolic links to your plugins and themes in these directories
    content: content

# Plugins
#
# Install and activate a list of plugins from wp.org
plugins:
    - akismet
    - code-snippets-extended
    - comment-moderation-e-mail-to-post-author
    - jetpack
    - language-fallback
    - more-privacy-options
    - multisite-enhancements
    - proper-network-activation
    - unconfirmed
    - wordpress-importer
